--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AuthorName/VirionName
branches:
  - main
projects:
  VirionName:
    model: virion
    type: library
    lint:
      phpstan: false
...